### ISSUE TITLE
Build the warning & error box-styles

### ISSUE THREAD

**Issue by mrfhitz** [mrfhitz/Rocket-Launch-Schedule#3]
The footer can be have one of three classes: `info`, `warning` & `error`. Depending on the used class the design should change. At the moment only the `info` class its defined: 

```css
footer.info {
    color: #909090;
    background-color: #ececec;
}

footer.info:hover {
    color: #464646;
    background-color: #ffffff;
}
```
